# To execute this docker-compose yml file use `docker-compose -f selenium-v1.yml up -d`
# To stop the execution, hit Ctrl+C, and then `docker-compose -f selenium-v1.yml down`
# This selenium application runs on the port 4444
# A video is recorded for each selenium script execution in /tmp/videos/
# By default, nodes start with a screen resolution of 1360 x 1020 with a color depth of 24 bits and a dpi of 96. These settings can be adjusted by specifying SE_SCREEN_WIDTH, SE_SCREEN_HEIGHT, SE_SCREEN_DEPTH, and/or SE_SCREEN_DPI environmental variables when starting the container.
# old node:4.3.0-20220726, video:ffmpeg-4.3.1-20220726, hub:4.3.0-20220726

version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.4.0-20220812
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      
  edge:
    image: selenium/node-edge:4.4.0-20220812
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      
  firefox:
    image: selenium/node-firefox:4.4.0-20220812
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      
  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20220812
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
      - VNC_NO_PASSWORD=1
      
  edge_video:
    image: selenium/video:ffmpeg-4.3.1-20220812
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - FILE_NAME=edge_video.mp4
      - VNC_NO_PASSWORD=1
      
  firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20220812
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=firefox_video.mp4
      - VNC_NO_PASSWORD=1
      
  selenium-hub:
    image: selenium/hub:4.4.0-20220812
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
